services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - odoo-db:/var/lib/postgresql/data
  odoo:
    image: odoo:18
    depends_on: [db]
    ports: ["8069:8069"]
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./:/mnt/extra-addons:ro
      - ./odoo.conf:/etc/odoo/odoo.conf:ro
      - odoo-data:/var/lib/odoo
volumes:
  odoo-db:
  odoo-data:
