from . import test_module
from . import test_app_banner
from . import test_app_benefit
from . import test_content_fields
from . import test_product_template
from . import test_controllers_base
from . import test_controllers_auth
from . import test_controllers_home
from . import test_controllers_devices
from . import test_controllers_catalog
from . import test_controllers_product
from . import test_controllers_cart
from . import test_controllers_checkout
from . import test_controllers_account
from . import test_controllers_address
from . import test_controllers_profile
